name = "MortgageCalculators"
uuid = "cbda39b7-a5b8-49f7-bf50-e22af4f2d7a9"
authors = ["Mark Kittisopikul <markkitt@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
FixedPointDecimals = "fb4d412d-6eee-574d-9565-ede6634db7b0"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
